// web/src/components/VmReinstallDialog.vue
<template>
  <el-dialog
    v-model="visible"
    title="重装系统"
    width="640px"
    append-to-body
    :close-on-click-modal="false"
    destroy-on-close
  >
    <el-alert type="warning" :closable="false" style="margin-bottom: 16px;">
      <template #title>
        重装会替换当前系统盘并自动删除全部快照，CPU、内存、网络和额外数据盘会保留，虚拟机会在任务开始时自动关机。
      </template>
    </el-alert>

    <el-form ref="formRef" :model="form" :rules="rules" label-width="120px">
      <el-form-item label="虚拟机名称">
        <el-input :model-value="vmName" disabled />
      </el-form-item>
      <el-form-item label="模板" prop="template">
        <el-select
          v-model="form.template"
          filterable
          clearable
          placeholder="请选择要重装的模板"
          style="width: 100%;"
          :loading="templateLoading"
          @change="handleTemplateChange"
        >
          <el-option
            v-for="item in templates"
            :key="item.name"
            :label="item.display_name || item.admin_name || item.name"
            :value="item.name"
          >
            <div class="template-option">
              <span>{{ item.display_name || item.admin_name || item.name }}</span>
              <span class="template-option-meta">{{ item.type || 'linux' }} / 最低 {{ resolveTemplateMinDiskSize(item) || '-' }} GB</span>
            </div>
          </el-option>
        </el-select>
      </el-form-item>
      <el-form-item label="系统盘大小" prop="disk_size">
        <el-input-number v-model="form.disk_size" :min="templateMinDiskSize || 1" :max="8192" :step="10" style="width: 100%;" />
        <div class="form-inline-hint">
          默认值为当前系统盘 {{ currentDiskSize || '-' }} GB；最低不能小于模板原始磁盘 {{ templateMinDiskSize || '-' }} GB。
        </div>
      </el-form-item>
      <el-form-item v-if="showCredentialFields" label="主机名" prop="hostname">
        <el-input v-model="form.hostname" placeholder="请输入重装后的主机名" />
      </el-form-item>
      <el-form-item v-if="showCredentialFields" label="登录用户名" prop="user">
        <el-input
          v-model="form.user"
          :disabled="isWindowsTemplate"
          :placeholder="isWindowsTemplate ? 'administrator' : '请输入登录用户名'"
        />
        <div class="form-inline-hint">
          <template v-if="isWindowsTemplate">Windows 模板固定使用 administrator。</template>
          <template v-else-if="isFnOSTemplate">FnOS 会把该账号写入为首次管理员账号。</template>
          <template v-else>仅支持小写字母、数字、下划线和短横线，且需以字母或下划线开头。</template>
        </div>
      </el-form-item>
      <el-form-item v-if="showCredentialFields" label="登录密码" prop="password">
        <el-input v-model="form.password" type="password" show-password placeholder="请输入强密码">
          <template #append>
            <el-button @click="generatePassword">随机强密码</el-button>
          </template>
        </el-input>
        <div class="form-inline-hint">
          {{ passwordHint }}
        </div>
      </el-form-item>
      <el-form-item v-if="isFnOSTemplate" label="FnOS 设备 ID">
        <el-radio-group v-model="form.fnos_device_id_mode">
          <el-radio label="regenerate">重新生成</el-radio>
          <el-radio label="preserve">保留模板设备 ID</el-radio>
          <el-radio label="custom">自定义</el-radio>
        </el-radio-group>
      </el-form-item>
      <el-form-item v-if="isFnOSTemplate && form.fnos_device_id_mode === 'custom'" label="自定义设备 ID" prop="fnos_device_id">
        <el-input v-model="form.fnos_device_id" placeholder="请输入 32 位或 40 位十六进制设备 ID" />
      </el-form-item>
      <el-form-item v-if="showCredentialFields" label="UserData">
        <el-input
          v-model="form.user_data"
          type="textarea"
          :rows="5"
          placeholder="cloud-init UserData（YAML/JSON 格式，可选）"
        />
        <div class="form-inline-hint">
          克隆时注入 cloud-init UserData。若以 #cloud-config 开头则替换默认配置，否则追加到默认配置后
        </div>
      </el-form-item>
    </el-form>

    <template #footer>
      <el-button @click="visible = false">取消</el-button>
      <el-button type="danger" :loading="submitting" @click="submitReinstall">提交重装任务</el-button>
    </template>
  </el-dialog>
</template>

<script setup>
import { computed, reactive, ref } from 'vue'
import { ElMessage } from 'element-plus'
import { getTemplateList, reinstallVm } from '@/api/vm'
import { passwordValidator, checkPasswordBreachAsync, generatePassword as genPwd, STRONG_PASSWORD_MIN_LENGTH, PASSWORD_ALLOWED_PATTERN } from '@/utils/validate'

const visible = ref(false)
const submitting = ref(false)
const templateLoading = ref(false)
const templates = ref([])
const currentVm = ref(null)
const formRef = ref(null)

const windowsTemplateUsername = 'administrator'
const usernamePattern = /^[a-z_][a-z0-9_-]{0,31}$/
const fnosDeviceIdPattern = /^[0-9a-fA-F]{32}([0-9a-fA-F]{8})?$/

const form = reactive({
  template: '',
  disk_size: 0,
  hostname: '',
  user: '',
  password: '',
  fnos_device_id_mode: 'regenerate',
  fnos_device_id: '',
  user_data: ''
})

const vmName = computed(() => currentVm.value?.name || '')
const currentDiskSize = computed(() => parseDiskSizeGB(currentVm.value?.disk_size))
const selectedTemplate = computed(() => templates.value.find(item => item.name === form.template) || null)
const selectedTemplateType = computed(() => `${selectedTemplate.value?.type || ''}`.trim().toLowerCase())
const templateMinDiskSize = computed(() => resolveTemplateMinDiskSize(selectedTemplate.value))
const showCredentialFields = computed(() => ['linux', 'windows', 'fnos'].includes(selectedTemplateType.value))
const isFnOSTemplate = computed(() => selectedTemplateType.value === 'fnos')
const isWindowsTemplate = computed(() => selectedTemplateType.value === 'windows')
const passwordHint = computed(() => `至少 ${STRONG_PASSWORD_MIN_LENGTH} 位（支持 !@#$%^&*_-+=?）`)

const rules = {
  template: [{ required: true, message: '请选择模板', trigger: 'change' }],
  disk_size: [{
    validator: (_rule, value, callback) => {
      const size = Number(value || 0)
      if (size <= 0) {
        callback(new Error('请设置系统盘大小'))
        return
      }
      if (templateMinDiskSize.value > 0 && size < templateMinDiskSize.value) {
        callback(new Error(`系统盘大小不能小于 ${templateMinDiskSize.value} GB`))
        return
      }
      callback()
    },
    trigger: 'change'
  }],
  hostname: [{
    validator: (_rule, value, callback) => {
      if (!showCredentialFields.value) {
        callback()
        return
      }
      if (!`${value || ''}`.trim()) {
        callback(new Error('请输入主机名'))
        return
      }
      callback()
    },
    trigger: 'blur'
  }],
  user: [{
    validator: (_rule, value, callback) => {
      if (!showCredentialFields.value || isWindowsTemplate.value) {
        callback()
        return
      }
      const normalized = `${value || ''}`.trim()
      if (!normalized) {
        callback(new Error('请输入登录用户名'))
        return
      }
      if (!usernamePattern.test(normalized)) {
        callback(new Error('用户名格式不正确'))
        return
      }
      callback()
    },
    trigger: 'blur'
  }],
  password: [{
    validator: (_rule, value, callback) => {
      if (!showCredentialFields.value) {
        callback()
        return
      }
      const normalized = `${value || ''}`
      if (!normalized) {
        callback(new Error('请输入登录密码'))
        return
      }
      passwordValidator(_rule, normalized, callback)
    },
    trigger: 'blur'
  }],
  fnos_device_id: [{
    validator: (_rule, value, callback) => {
      if (!isFnOSTemplate.value || form.fnos_device_id_mode !== 'custom') {
        callback()
        return
      }
      const normalized = `${value || ''}`.trim()
      if (!normalized) {
        callback(new Error('请输入自定义设备 ID'))
        return
      }
      if (!fnosDeviceIdPattern.test(normalized)) {
        callback(new Error('设备 ID 只能为 32 位或 40 位十六进制字符串'))
        return
      }
      callback()
    },
    trigger: 'blur'
  }]
}

function parseDiskSizeGB(value) {
  const text = `${value || ''}`.trim()
  const matched = text.match(/([\d.]+)\s*GB/i)
  if (!matched) {
    return 0
  }
  const parsed = Number.parseFloat(matched[1])
  if (!Number.isFinite(parsed) || parsed <= 0) {
    return 0
  }
  return Math.ceil(parsed)
}

function resolveTemplateMinDiskSize(template) {
  if (!template) {
    return 0
  }
  const text = `${template.virtual_size || ''}`.trim()
  const gibMatch = text.match(/([\d.]+)\s*GiB/i)
  if (gibMatch) {
    const parsed = Number.parseFloat(gibMatch[1])
    return Number.isFinite(parsed) && parsed > 0 ? Math.ceil(parsed) : 0
  }
  const gbMatch = text.match(/([\d.]+)\s*GB/i)
  if (gbMatch) {
    const parsed = Number.parseFloat(gbMatch[1])
    return Number.isFinite(parsed) && parsed > 0 ? Math.ceil(parsed) : 0
  }
  return 0
}

async function fetchTemplates() {
  templateLoading.value = true
  try {
    const res = await getTemplateList()
    templates.value = Array.isArray(res.data) ? res.data : []
  } finally {
    templateLoading.value = false
  }
}

function resetForm(vm = {}) {
  form.template = ''
  form.disk_size = parseDiskSizeGB(vm.disk_size) || 0
  form.hostname = vm.name || ''
  form.user = ''
  form.password = ''
  form.fnos_device_id_mode = 'regenerate'
  form.fnos_device_id = ''
  form.user_data = ''
}

function applyTemplateDefaults() {
  if (isWindowsTemplate.value) {
    form.user = windowsTemplateUsername
  } else if (selectedTemplate.value?.template_user) {
    form.user = selectedTemplate.value.template_user
  } else if (!form.user) {
    form.user = ''
  }
  if (templateMinDiskSize.value > 0 && form.disk_size < templateMinDiskSize.value) {
    form.disk_size = templateMinDiskSize.value
  }
  if (!isFnOSTemplate.value) {
    form.fnos_device_id_mode = 'regenerate'
    form.fnos_device_id = ''
  }
}

function handleTemplateChange() {
  applyTemplateDefaults()
}

function generatePassword() {
  form.password = genPwd()
  formRef.value?.validateField('password').catch(() => false)
}

async function submitReinstall() {
  if (!formRef.value) {
    return
  }
  const valid = await formRef.value.validate().catch(() => false)
  if (!valid) {
    return
  }
  // 异步泄露密码检测（HIBP API）
  if (form.password) {
    const breach = await checkPasswordBreachAsync(form.password)
    if (breach.enabled && breach.breached) {
      ElMessage.error('该密码已在已知泄露数据库中发现，请更换为更安全的密码')
      return
    }
  }
  submitting.value = true
  try {
    await reinstallVm(vmName.value, {
      template: form.template,
      disk_size: Number(form.disk_size || 0),
      hostname: `${form.hostname || ''}`.trim(),
      user: isWindowsTemplate.value ? windowsTemplateUsername : `${form.user || ''}`.trim(),
      password: form.password,
      preserve_fnos_device_id: isFnOSTemplate.value && (form.fnos_device_id_mode === 'preserve' || form.fnos_device_id_mode === 'custom'),
      fnos_device_id: isFnOSTemplate.value && form.fnos_device_id_mode === 'custom' ? `${form.fnos_device_id || ''}`.trim() : '',
      user_data: form.user_data || undefined
    })
    ElMessage.success('重装任务已提交，请在任务中心查看进度')
    visible.value = false
    emit('success')
  } finally {
    submitting.value = false
  }
}

async function open(vm) {
  currentVm.value = vm || {}
  resetForm(currentVm.value)
  visible.value = true
  await fetchTemplates()
  const currentTemplate = `${currentVm.value?.template || ''}`.trim()
  if (currentTemplate && templates.value.some(item => item.name === currentTemplate)) {
    form.template = currentTemplate
  }
  applyTemplateDefaults()
}

const emit = defineEmits(['success'])

defineExpose({
  open
})
</script>

<style scoped>
.template-option {
  display: flex;
  justify-content: space-between;
  gap: 12px;
}

.template-option-meta {
  color: var(--el-text-color-secondary);
  font-size: 12px;
}

.form-inline-hint {
  color: var(--el-text-color-secondary);
  font-size: 12px;
  line-height: 1.5;
  margin-top: 4px;
}
</style>

// web/src/views/vm/dialogs/VmReinstallDialog.tsx
/**
 * 重装系统弹窗
 * 迁移自旧前端 VmReinstallDialog.vue
 */
import { useEffect, useMemo, useState } from 'react'
import {
  Banner,
  Button,
  Input,
  InputNumber,
  Modal,
  Radio,
  Select,
  Toast,
} from '@douyinfe/semi-ui'
import type { VmListItem } from '@/api/vm'
import { reinstallVm } from '@/api/vm'
import { getTemplateList, type TemplateItem } from '@/api/template'
import {
  checkPasswordBreachAsync,
  generatePassword,
  validatePassword,
  STRONG_PASSWORD_MIN_LENGTH,
  PASSWORD_ALLOWED_PATTERN,
} from '@/utils/validate'
import { parseDiskSizeGB, resolveTemplateMinDiskSize } from '../utils'
import { useMountModalLifecycle } from '@/hooks/useMountModalLifecycle'

interface VmReinstallDialogProps {
  vm: VmListItem
  onClose: () => void
  onSuccess: () => void
}

const WINDOWS_USERNAME = 'administrator'
const USERNAME_PATTERN = /^[a-z_][a-z0-9_-]{0,31}$/
const FNOS_DEVICE_ID_PATTERN = /^[0-9a-fA-F]{32}([0-9a-fA-F]{8})?$/

export default function VmReinstallDialog({ vm, onClose, onSuccess }: VmReinstallDialogProps) {
  const { modalVisible, requestClose, afterModalClose } = useMountModalLifecycle(onClose)
  const [templates, setTemplates] = useState<TemplateItem[]>([])
  const [templateLoading, setTemplateLoading] = useState(false)
  const [submitting, setSubmitting] = useState(false)

  const [template, setTemplate] = useState('')
  const [diskSize, setDiskSize] = useState<number>(parseDiskSizeGB(vm.disk_size) || 0)
  const [hostname, setHostname] = useState(vm.name || '')
  const [user, setUser] = useState('')
  const [password, setPassword] = useState('')
  const [fnosDeviceIdMode, setFnosDeviceIdMode] = useState<'regenerate' | 'preserve' | 'custom'>(
    'regenerate',
  )
  const [fnosDeviceId, setFnosDeviceId] = useState('')

  const currentDiskSize = useMemo(() => parseDiskSizeGB(vm.disk_size), [vm.disk_size])
  const selectedTemplate = useMemo(
    () => templates.find((item) => item.name === template) || null,
    [templates, template],
  )
  const templateType = (selectedTemplate?.type || '').trim().toLowerCase()
  const templateMinDiskSize = resolveTemplateMinDiskSize(selectedTemplate)
  const showCredentialFields = ['linux', 'windows', 'fnos'].includes(templateType)
  const isFnos = templateType === 'fnos'
  const isWindows = templateType === 'windows'

  // 加载模板列表并预选当前模板
  useEffect(() => {
    let cancelled = false
    setTemplateLoading(true)
    getTemplateList()
      .then((res) => {
        if (cancelled) return
        const items = Array.isArray(res.data) ? res.data : []
        setTemplates(items)
        const currentTemplate = (vm.template || '').trim()
        if (currentTemplate && items.some((item) => item.name === currentTemplate)) {
          setTemplate(currentTemplate)
        }
      })
      .catch((err) => console.error('获取模板列表失败', err))
      .finally(() => {
        if (!cancelled) setTemplateLoading(false)
      })
    return () => {
      cancelled = true
    }
  }, [vm.template])

  // 切换模板时应用默认值
  useEffect(() => {
    if (isWindows) {
      setUser(WINDOWS_USERNAME)
    } else if (selectedTemplate?.template_user) {
      setUser(selectedTemplate.template_user)
    }
    if (templateMinDiskSize > 0 && diskSize < templateMinDiskSize) {
      setDiskSize(templateMinDiskSize)
    }
    if (!isFnos) {
      setFnosDeviceIdMode('regenerate')
      setFnosDeviceId('')
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [template, templates])

  const validate = (): boolean => {
    if (!template) {
      Toast.warning('请选择要重装的模板')
      return false
    }
    if (!diskSize || diskSize <= 0) {
      Toast.warning('请设置系统盘大小')
      return false
    }
    if (templateMinDiskSize > 0 && diskSize < templateMinDiskSize) {
      Toast.warning(`系统盘大小不能小于 ${templateMinDiskSize} GB`)
      return false
    }
    if (showCredentialFields) {
      if (!hostname.trim()) {
        Toast.warning('请输入主机名')
        return false
      }
      if (!isWindows && !USERNAME_PATTERN.test(user.trim())) {
        Toast.warning('用户名仅支持小写字母、数字、下划线和短横线，且需以字母或下划线开头')
        return false
      }
      if (!password) {
        Toast.warning('请输入登录密码')
        return false
      }
      if (password.length < STRONG_PASSWORD_MIN_LENGTH || !PASSWORD_ALLOWED_PATTERN.test(password)) {
        Toast.warning(`密码至少 ${STRONG_PASSWORD_MIN_LENGTH} 位，只支持字母、数字和 !@#$%^&*_-+=? 符号`)
        return false
      }
      if (!validatePassword(password).valid) {
        Toast.warning('该密码过于常见，请更换为更安全的密码')
        return false
      }
    }
    if (isFnos && fnosDeviceIdMode === 'custom') {
      if (!FNOS_DEVICE_ID_PATTERN.test(fnosDeviceId.trim())) {
        Toast.warning('设备 ID 只能为 32 位或 40 位十六进制字符串')
        return false
      }
    }
    return true
  }

  const handleSubmit = async () => {
    if (!validate()) return
    // 异步泄露密码检测（HIBP）
    if (password) {
      const breach = await checkPasswordBreachAsync(password)
      if (breach.enabled && breach.breached) {
        Toast.error('该密码已在已知泄露数据库中发现，请更换为更安全的密码')
        return
      }
    }
    setSubmitting(true)
    try {
      await reinstallVm(vm.name, {
        template,
        disk_size: Number(diskSize || 0),
        hostname: hostname.trim(),
        user: isWindows ? WINDOWS_USERNAME : user.trim(),
        password,
        preserve_fnos_device_id: isFnos && fnosDeviceIdMode !== 'regenerate',
        fnos_device_id: isFnos && fnosDeviceIdMode === 'custom' ? fnosDeviceId.trim() : '',
      })
      Toast.success('重装任务已提交，请在任务中心查看进度')
      requestClose()
      onSuccess()
    } catch {
      // 错误提示由请求层统一处理
    } finally {
      setSubmitting(false)
    }
  }

  return (
    <Modal
      title="重装系统"
      visible={modalVisible}
      afterClose={afterModalClose}
      onCancel={requestClose}
      onOk={() => void handleSubmit()}
      okText="提交重装任务"
      cancelText="取消"
      okButtonProps={{ type: 'danger' }}
      confirmLoading={submitting}
      width={640}
      closeOnEsc
    >
      <Banner
        type="warning"
        closeIcon={null}
        style={{ marginBottom: 16 }}
        description="重装会替换当前系统盘并自动删除全部快照，CPU、内存、网络和额外数据盘会保留，虚拟机会在任务开始时自动关机。"
      />

      <div className="qvm-form-item">
        <div className="qvm-form-label">虚拟机名称</div>
        <Input value={vm.name} disabled />
      </div>
      <div className="qvm-form-item">
        <div className="qvm-form-label required">模板</div>
        <Select
          style={{ width: '100%' }}
          value={template || undefined}
          onChange={(value) => setTemplate(value as string)}
          filter
          showClear
          loading={templateLoading}
          placeholder="请选择要重装的模板"
          optionList={templates.map((item) => ({
            label: item.display_name || item.admin_name || item.name,
            value: item.name,
          }))}
        />
        {selectedTemplate && (
          <div className="qvm-form-tip">
            {selectedTemplate.type || 'linux'} / 最低 {templateMinDiskSize || '-'} GB
          </div>
        )}
      </div>
      <div className="qvm-form-item">
        <div className="qvm-form-label required">系统盘大小</div>
        <InputNumber
          style={{ width: '100%' }}
          value={diskSize}
          onChange={(value) => setDiskSize(Number(value || 0))}
          min={templateMinDiskSize || 1}
          max={8192}
          step={10}
          suffix="GB"
        />
        <div className="qvm-form-tip">
          默认值为当前系统盘 {currentDiskSize || '-'} GB；最低不能小于模板原始磁盘{' '}
          {templateMinDiskSize || '-'} GB。
        </div>
      </div>

      {showCredentialFields && (
        <>
          <div className="qvm-form-item">
            <div className="qvm-form-label required">主机名</div>
            <Input value={hostname} onChange={setHostname} placeholder="请输入重装后的主机名" />
          </div>
          <div className="qvm-form-item">
            <div className="qvm-form-label required">登录用户名</div>
            <Input
              value={user}
              onChange={setUser}
              disabled={isWindows}
              placeholder={isWindows ? WINDOWS_USERNAME : '请输入登录用户名'}
            />
            <div className="qvm-form-tip">
              {isWindows
                ? 'Windows 模板固定使用 administrator。'
                : isFnos
                  ? 'FnOS 会把该账号写入为首次管理员账号。'
                  : '仅支持小写字母、数字、下划线和短横线，且需以字母或下划线开头。'}
            </div>
          </div>
          <div className="qvm-form-item">
            <div className="qvm-form-label required">登录密码</div>
            <Input
              mode="password"
              value={password}
              onChange={setPassword}
              placeholder="请输入强密码"
            />
            <div className="qvm-form-tip-row">
              <span className="qvm-form-tip">至少 {STRONG_PASSWORD_MIN_LENGTH} 位（支持 !@#$%^&*_-+=?）</span>
              <Button
                size="small"
                theme="borderless"
                type="primary"
                onClick={() => setPassword(generatePassword())}
              >
                随机强密码
              </Button>
            </div>
          </div>
        </>
      )}

      {isFnos && (
        <div className="qvm-form-item">
          <div className="qvm-form-label">FnOS 设备 ID</div>
          <Radio.Group
            value={fnosDeviceIdMode}
            onChange={(e) => setFnosDeviceIdMode(e.target.value as typeof fnosDeviceIdMode)}
          >
            <Radio value="regenerate">重新生成</Radio>
            <Radio value="preserve">保留模板设备 ID</Radio>
            <Radio value="custom">自定义</Radio>
          </Radio.Group>
        </div>
      )}
      {isFnos && fnosDeviceIdMode === 'custom' && (
        <div className="qvm-form-item">
          <div className="qvm-form-label required">自定义设备 ID</div>
          <Input
            value={fnosDeviceId}
            onChange={setFnosDeviceId}
            placeholder="请输入 32 位或 40 位十六进制设备 ID"
          />
        </div>
      )}
    </Modal>
  )
}
